.TH pkt2flow 1 "August 2025" "pkt2flow 1.2.0" "User Commands"
.SH NAME
pkt2flow \- split packets in pcap into per-flow pcaps
.SH SYNOPSIS
.B pkt2flow
.RI [ options ]
.RI "pcapfile"
.SH DESCRIPTION
A simple utility to classify packets into flows using the 4-tuple
(source IP, destination IP, source port, destination port) and write each
flow to a separate pcap file.
.SH OPTIONS
.TP
.B -h
Print help and exit.
.TP
.B -u
Also dump UDP flows.
.TP
.B -v
Also dump invalid TCP flows without the SYN option.
.TP
.B -x
Also dump non-UDP/non-TCP IP flows.
.TP
.B -o DIR
Output directory.
.SH AUTHOR
Xumin Chen <chenxm35@gmail.com>
